#SingleInstance Force
#Persistent
; =====================================================================
; Auto-generated by AHK Manager - 2025-11-12 20:25:49
; =====================================================================

if not A_IsAdmin
{
   Run *RunAs "%A_ScriptFullPath%"  ; Bắt buộc chạy lại bằng quyền Admin
   ExitApp
}

; Loại trừ các ứng dụng game - sử dụng #IfWinNotActive
; Lưu ý: Trong AutoHotkey v1, khi có nhiều #IfWinNotActive liên tiếp, chúng được xử lý như điều kiện AND
; Nghĩa là hotkeys chỉ hoạt động khi KHÔNG có BẤT KỲ window nào trong danh sách đang active
#IfWinNotActive, ahk_exe ONCE_HUMAN.exe
#IfWinNotActive, ahk_exe DeltaForceClient-Win64-Shipping.exe
#IfWinNotActive, ahk_exe df_garena_launcher.exe
#IfWinNotActive, ahk_exe DeltaForce.exe
#IfWinNotActive, ahk_exe ONCE_HUMAN
#IfWinNotActive, ahk_exe DeltaForceClient-Win64-Shipping
#IfWinNotActive, ahk_exe df_garena_launcher
#IfWinNotActive, ahk_exe DeltaForce
#IfWinNotActive, Delta Force
#IfWinNotActive, Garena Delta Force

; CÁC PHÍM TẮT & HOTSTRING SẼ BỊ VÔ HIỆU HÓA KHI DÙNG LDPLAYER
::xx::
Sendinput Pé đến gặp a trực tiếp ok hết rồi a thanh toán cho pé tại phòng phục vụ a nha
sleep 100
return

::ww::
SendMode Input
Send, Hi, Where are you from?
sleep 100
return

::dd::
Sendinput Do you want massage?
sleep 100
return

::ss::
Sendinput Meet not same or don't like you can cancel and don't need to pay anything
sleep 100
return

::qq::
SendMode Input
Send, We can meet first for you see me direct before deal, if meet and don't like you can reject and don't need to pay anything
sleep 100
return

::nn::
SendMode Input
Send, VietNam, Nice to meet you
sleep 100
return

::ii::
SendMode Input
Send, Send me address if you need, I can come to you
sleep 100
return

::,,::
SendMode Input
Send, Please choose a girl and she can come to your hotel or apartment
sleep 100
return

::mm::
SendMode Input
Send, My photos
sleep 100
return

::cc::
SendMode Input
Send, Can you take shot a photo of your key room and send it to me?
sleep 100
return

::ll::
SendMode Input
Send, Text me know when you need, I will come to you
sleep 100
return

::bb::
Sendinput Dịch vụ bao gồm mát xa body nude thư giãn, tắm chung và làm tình với pé ạ
sleep 100
return

::vv::
Sendinput Nào a cần a nói em nha, E đến tận nơi qua a
sleep 100
return

::ee::
Sendinput Hi A. A ở đâu vậy?
sleep 100
return

::oo::
Sendinput 1,5 milion for hour, 3,5 milion for overnight, Mαssαgє with sєx
sleep 100
return

::tt::
Sendinput E có dịch vụ mát xa làm tình giá 1tr5 1 giờ, qua đêm là 3tr5
sleep 100
return

::t1::
Sendinput A cần thì chọn 1 pé, pé đến tận nơi qua nha
sleep 100
return

::o3::
Sendinput 1.3 milions vnd for hour and 3 milions for overnight. Massage and Make love
sleep 100
return

::rr::
Sendinput Em nhận đi khách giá 1tr5 1 giờ, qua đêm là 3tr5, A cần nói em nha
sleep 100
return

::hh::
Sendinput Ảnh của em a xem nhé
sleep 100
return

::kk::
Sendinput Dạ a cần thì lấy phòng ks nào cũng đc rồi pé đến nha
sleep 100
return

::gg::
Sendinput Gặp không giống hay a ko thích a có quyền từ chối và ko cần trả tiền pé gì hết. A yên tâm nhé
sleep 100
return

::pp::
Sendinput A cần thì chọn một pé, pé sẽ đến tận nơi a nha
sleep 100
return

::jj::
Sendinput Phiền a chụp giúp thẻ phòng gửi qua em để pé xác nhận qua a nha
sleep 100
return

^2::
Sendinput https://github.com/Sxcution/Mon
sleep 100
return

^3::
Sendinput https://github.com/monsxcution/STool_v2
sleep 100
return

!g::
Sendinput Dạ giá e đã bao gồm tất cả rồi không thêm gì a nha, a thấy pé phục vụ a tốt a có thể cho thêm hoặc ko tùy a nha
sleep 100
return

; =====================================================================
; Chat Tool - Random Từ Ngữ (Ctrl + 0)
; =====================================================================
^5::
    ; Danh sách từ (có thể thêm/sửa tùy ý) - Khoảng 60 từ
    words := "hello|hi|you|love|xinh|good|fine|chào|yêu|đẹp|ok|yes|no|thank|cảm ơn|baby|nice|like|bye|xu|rãnh|xênh|đáng|ốn|trăng|trời|sao|gió|mây|ngủ|nghĩ|nằm|ngồi|thức|đi|về|ăn|uống|chơi|học|làm|nói|nghe|nhìn|thấy|biết|hiểu|muốn|cần|thích|ghét|vui|buồn|hạnh phúc|lo lắng|bình yên|tự do|ước mơ|hy vọng"
    
    ; Đếm số từ
    StringSplit, wordArray, words, |
    wordCount := wordArray0
    
    ; Kiểm tra danh sách từ có rỗng không
    if (wordCount = 0) {
        return
    }
    
    ; Random số từ (1-5)
    Random, numWords, 1, 5
    
    ; Giới hạn số từ không vượt quá số từ có sẵn
    if (numWords > wordCount) {
        numWords := wordCount
    }
    
    ; Chọn random từ (tránh trùng lặp)
    selectedIndices := ""
    selectedCount := 0
    
    Loop, 100 {  ; Giới hạn 100 lần thử để tránh vòng lặp vô hạn
        if (selectedCount >= numWords) {
            Break
        }
        
        Random, randomIndex, 1, %wordCount%
        
        ; Kiểm tra xem index đã được chọn chưa
        found := false
        if (selectedIndices != "") {
            StringSplit, indexArray, selectedIndices, |
            Loop, %indexArray0% {
                if (indexArray%A_Index% = randomIndex) {
                    found := true
                    Break
                }
            }
        }
        
        ; Nếu chưa chọn thì thêm vào
        if (!found) {
            if (selectedIndices = "") {
                selectedIndices := randomIndex
            } else {
                selectedIndices := selectedIndices . "|" . randomIndex
            }
            selectedCount++
        }
    }
    
    ; Lấy các từ đã chọn
    StringSplit, indexArray, selectedIndices, |
    selectedWords := ""
    Loop, %indexArray0% {
        wordIndex := indexArray%A_Index%
        selectedWord := wordArray%wordIndex%
        if (selectedWords = "") {
            selectedWords := selectedWord
        } else {
            selectedWords := selectedWords . "|" . selectedWord
        }
    }
    
    ; Xáo trộn thứ tự (shuffle) - Fisher-Yates
    StringSplit, selectedArray, selectedWords, |
    selectedCount := selectedArray0
    
    Loop, %selectedCount% - 1 {
        Random, j, %A_Index%, %selectedCount%
        temp := selectedArray%A_Index%
        selectedArray%A_Index% := selectedArray%j%
        selectedArray%j% := temp
    }
    
    ; Gõ từng từ đã xáo trộn (ngăn cách bởi dấu cách)
    SendMode Input
    Loop, %selectedCount% {
        if (A_Index > 1) {
            Send, {Space}
        }
        SendInput, % selectedArray%A_Index%
    }
    
return

#IfWinActive