#SingleInstance Force
#Persistent
; =====================================================================
; Auto-generated by AHK Manager - 2025-11-12 20:25:49
; =====================================================================

if not A_IsAdmin
{
   Run *RunAs "%A_ScriptFullPath%"  ; Bắt buộc chạy lại bằng quyền Admin
   ExitApp
}

; Tạo nhóm các game cần loại trừ
GroupAdd, ExcludedGames, ahk_exe ONCE_HUMAN.exe
GroupAdd, ExcludedGames, ahk_exe DeltaForceClient-Win64-Shipping.exe
GroupAdd, ExcludedGames, ahk_exe df_garena_launcher.exe
GroupAdd, ExcludedGames, ahk_exe DeltaForce.exe
GroupAdd, ExcludedGames, ahk_exe ONCE_HUMAN
GroupAdd, ExcludedGames, ahk_exe DeltaForceClient-Win64-Shipping
GroupAdd, ExcludedGames, ahk_exe df_garena_launcher
GroupAdd, ExcludedGames, Delta Force
GroupAdd, ExcludedGames, Garena Delta Force

; Chỉ kích hoạt các hotkey/hotstring bên dưới nếu KHÔNG phải là các game trong nhóm ExcludedGames
#IfWinNotActive, ahk_group ExcludedGames

SendQuickText(text) {
    DebugLog("SendQuickText triggered -> " . text)
    ClipSaved := ClipboardAll
    Clipboard := text
    ClipWait, 0.5, 1
    if (ErrorLevel) {
        DebugLog("Clipboard not ready, fallback to SendRaw")
        SendRaw, %text%
    } else {
        SendInput, ^v
    }
    Sleep, 100
    Clipboard := ClipSaved
    VarSetCapacity(ClipSaved, 0)
}

DebugLog(message) {
    OutputDebug, 🔍 %message%
}

; =====================================================================
; LAUNCHER HOTKEYS
; =====================================================================

PgUp::
    RunAsUser("C:\Users\Mon\AppData\Local\Programs\Python\Python311\pythonw.exe", "c:\Users\Mon\Desktop\Mon\Main\Main.pyw", "c:\Users\Mon\Desktop\Mon\Main")
return

RunAsUser(Target, Args := "", WorkingDir := "") {
    ; Get the ShellWindows collection
    shellWindows := ComObjCreate("Shell.Application").Windows
    
    ; Find the desktop window (SWC_DESKTOP = 8, SWFO_NEEDDISPATCH = 1)
    desktop := shellWindows.FindWindowSW(0, 0, 8, 0, 1)
    
    ; Check if we successfully got the desktop object
    if (desktop) {
        ; Use the desktop's application object to execute the command
        ; This inherits the user's privileges (Medium Integrity)
        desktop.Document.Application.ShellExecute(Target, Args, WorkingDir, "open", 1)
    } else {
        ; Fallback: If desktop not found, run normally (might be elevated)
        Run, %Target% %Args%, %WorkingDir%
    }
}

; CÁC PHÍM TẮT & HOTSTRING SẼ BỊ VÔ HIỆU HÓA KHI DÙNG LDPLAYER
::xx::
    SendQuickText("Pé đến gặp a trực tiếp ok hết rồi a thanh toán cho pé tại phòng phục vụ a nha")
return

::ww::
    SendQuickText("Hi, Where are you from?")
return

::dd::
    SendQuickText("Do you want massage?")
return

::ss::
    SendQuickText("Meet not same or don't like you can cancel and don't need to pay anything")
return

::qq::
    SendQuickText("We can meet first for you see me direct before deal, if meet and don't like you can reject and don't need to pay anything")
return

::nn::
    SendQuickText("VietNam, Nice to meet you")
return

::ii::
    SendQuickText("Send me address if you need, I can come to you")
return

::,,::
    SendQuickText("Please choose a girl and she can come to your hotel or apartment")
return

::mm::
    SendQuickText("My photos")
return

::cc::
    SendQuickText("Can you take shot a photo of your key room and send it to me?")
return

::ll::
    SendQuickText("Text me know when you need, I will come to you")
return

::bb::
    SendQuickText("Dịch vụ bao gồm mát xa body nude thư giãn, tắm chung và làm tình với pé ạ")
return

::vv::
    SendQuickText("Nào a cần a nói em nha, E đến tận nơi qua a")
return

::ee::
    SendQuickText("Hi A. A ở đâu vậy?")
return

::oo::
    SendQuickText("1,5 milion for hour, 3,5 milion for overnight, Mαssαgє with sєx")
return

::tt::
    SendQuickText("E có dịch vụ mát xa làm tình giá 1tr5 1 giờ, qua đêm là 3tr5")
return

::t1::
    SendQuickText("A cần thì chọn 1 pé, pé đến tận nơi qua nha")
return

::o3::
    SendQuickText("1.3 milions vnd for hour and 3 milions for overnight. Massage and Make love")
return

::rr::
    SendQuickText("Em nhận đi khách giá 1tr5 1 giờ, qua đêm là 3tr5, A cần nói em nha")
return

::hh::
    SendQuickText("Ảnh của em a xem nhé")
return

::kk::
    SendQuickText("Dạ a cần thì lấy phòng ks nào cũng đc rồi pé đến nha")
return

::gg::
    SendQuickText("Gặp không giống hay a ko thích a có quyền từ chối và ko cần trả tiền pé gì hết. A yên tâm nhé")
return

::pp::
    SendQuickText("A cần thì chọn một pé, pé sẽ đến tận nơi a nha")
return

::jj::
    SendQuickText("Phiền a chụp giúp thẻ phòng gửi qua em để pé xác nhận qua a nha")
return

^2::
Sendinput https://github.com/Sxcution/Mon
sleep 100
return

^3::
Sendinput https://github.com/monsxcution/STool_v2
sleep 100
return

; Random words generator (Wrapped in hotkey to prevent auto-exec)
^4::
    ; Danh sách từ (có thể thêm/sửa tùy ý) - Khoảng 60 từ
    words := "hello|hi|you|love|xinh|good|fine|chào|yêu|đẹp|ok|yes|no|thank|cảm ơn|baby|nice|like|bye|xu|rãnh|xênh|đáng|ốn|trăng|trời|sao|gió|mây|ngủ|nghĩ|nằm|ngồi|thức|đi|về|ăn|uống|chơi|học|làm|nói|nghe|nhìn|thấy|biết|hiểu|muốn|cần|thích|ghét|vui|buồn|hạnh phúc|lo lắng|bình yên|tự do|ước mơ|hy vọng"
    
    ; Đếm số từ
    StringSplit, wordArray, words, |
    wordCount := wordArray0
    
    ; Kiểm tra danh sách từ có rỗng không
    if (wordCount = 0) {
        return
    }
    
    ; Random số từ (1-5)
    Random, numWords, 1, 5
    
    ; Giới hạn số từ không vượt quá số từ có sẵn
    if (numWords > wordCount) {
        numWords := wordCount
    }
    
    ; Chọn random từ (tránh trùng lặp)
    selectedIndices := ""
    selectedCount := 0
    
    Loop, 100 {  ; Giới hạn 100 lần thử để tránh vòng lặp vô hạn
        if (selectedCount >= numWords) {
            Break
        }
        
        Random, randomIndex, 1, %wordCount%
        
        ; Kiểm tra xem index đã được chọn chưa
        found := false
        if (selectedIndices != "") {
            StringSplit, indexArray, selectedIndices, |
            Loop, %indexArray0% {
                if (indexArray%A_Index% = randomIndex) {
                    found := true
                    Break
                }
            }
        }
        
        ; Nếu chưa chọn thì thêm vào
        if (!found) {
            if (selectedIndices = "") {
                selectedIndices := randomIndex
            } else {
                selectedIndices := selectedIndices . "|" . randomIndex
            }
            selectedCount++
        }
    }
    
    ; Lấy các từ đã chọn
    StringSplit, indexArray, selectedIndices, |
    selectedWords := ""
    Loop, %indexArray0% {
        wordIndex := indexArray%A_Index%
        selectedWord := wordArray%wordIndex%
        if (selectedWords = "") {
            selectedWords := selectedWord
        } else {
            selectedWords := selectedWords . "|" . selectedWord
        }
    }
    
    ; Xáo trộn thứ tự (shuffle) - Fisher-Yates
    StringSplit, selectedArray, selectedWords, |
    selectedCount := selectedArray0
    
    Loop, %selectedCount% - 1 {
        Random, j, %A_Index%, %selectedCount%
        temp := selectedArray%A_Index%
        selectedArray%A_Index% := selectedArray%j%
        selectedArray%j% := temp
    }
    
    ; Gõ từng từ đã xáo trộn (ngăn cách bởi dấu cách)
    SendMode Input
    Loop, %selectedCount% {
        if (A_Index > 1) {
            Send, {Space}
        }
        SendInput, % selectedArray%A_Index%
    }
return

#IfWinActive

; =====================================================================
; ONCE HUMAN SPECIFIC HOTKEYS
; =====================================================================
; Load Settings from INI file (Default to 1 if not found)
IniRead, EnableAutoWalk, MonAHK_Settings.ini, OnceHuman, EnableAutoWalk, 1
IniRead, EnableAutoFarm, MonAHK_Settings.ini, OnceHuman, EnableAutoFarm, 1
IniRead, EnableAutoSpace, MonAHK_Settings.ini, OnceHuman, EnableAutoSpace, 1
IniRead, EnableAutoClick, MonAHK_Settings.ini, OnceHuman, EnableAutoClick, 1

; --- Hotkeys with Conditional Logic ---

; Only activate Middle Mouse hook if Game is Active AND Feature is Enabled
#If WinActive("ahk_exe ONCE_HUMAN.exe") && EnableAutoClick
MButton::
    if (GetKeyState("LButton")) {
        Click, Up
    } else {
        Click, Down
    }
return
#If

; Only activate Numpad+ hook if Game is Active AND Feature is Enabled
#If WinActive("ahk_exe ONCE_HUMAN.exe") && EnableAutoWalk
NumpadAdd::
    GoSub, ToggleAutoWalk
return
#If

; Only activate Alt+F hook if Game is Active AND Feature is Enabled
#If WinActive("ahk_exe ONCE_HUMAN.exe") && EnableAutoFarm
!f::
    GoSub, ToggleAutoFarm
return
#If

; Only activate Alt+Space hook if Game is Active AND Feature is Enabled
#If WinActive("ahk_exe ONCE_HUMAN.exe") && EnableAutoSpace
!Space::
    GoSub, ToggleAutoSpace
return
#If

; Menu Hotkey (Always Active in Game)
#If WinActive("ahk_exe ONCE_HUMAN.exe")
F5::
    ; Destroy previous GUI to ensure fresh state
    Gui, OnceHuman:Destroy
    Gui, OnceHuman:New, +AlwaysOnTop +ToolWindow, Once Human Menu
    Gui, OnceHuman:Font, s10, Segoe UI
    
    Gui, OnceHuman:Add, Text, x10 y10, Master Switches (Enable/Disable Hotkeys):
    
    ; Checkbox Auto Walk
    Gui, OnceHuman:Add, Checkbox, x20 y+10 vCbEnableAutoWalk gGuiUpdateSwitches Checked%EnableAutoWalk%, Enable Auto Walk (Numpad +)
    
    ; Checkbox Auto Farm
    Gui, OnceHuman:Add, Checkbox, x20 y+10 vCbEnableAutoFarm gGuiUpdateSwitches Checked%EnableAutoFarm%, Enable Auto Farm (Alt + F)

    ; Checkbox Auto Space
    Gui, OnceHuman:Add, Checkbox, x20 y+10 vCbEnableAutoSpace gGuiUpdateSwitches Checked%EnableAutoSpace%, Enable Auto Space (Alt + Space)

    ; Checkbox Auto Click
    Gui, OnceHuman:Add, Checkbox, x20 y+10 vCbEnableAutoClick gGuiUpdateSwitches Checked%EnableAutoClick%, Enable Auto Click (Middle Mouse)
    
    Gui, OnceHuman:Show, x0 y0 NoActivate, Once Human Controls
return
#If

; --- Subroutines ---

GuiUpdateSwitches:
    Gui, OnceHuman:Submit, NoHide
    EnableAutoWalk := CbEnableAutoWalk
    EnableAutoFarm := CbEnableAutoFarm
    EnableAutoSpace := CbEnableAutoSpace
    EnableAutoClick := CbEnableAutoClick
    
    ; Save Settings to INI
    IniWrite, %EnableAutoWalk%, MonAHK_Settings.ini, OnceHuman, EnableAutoWalk
    IniWrite, %EnableAutoFarm%, MonAHK_Settings.ini, OnceHuman, EnableAutoFarm
    IniWrite, %EnableAutoSpace%, MonAHK_Settings.ini, OnceHuman, EnableAutoSpace
    IniWrite, %EnableAutoClick%, MonAHK_Settings.ini, OnceHuman, EnableAutoClick
    
    ; Safety: If disabled, stop any running actions immediately
    if (!EnableAutoWalk && AutoWalkState) {
        Send, {w up}
        AutoWalkState := 0
    }
    if (!EnableAutoFarm && AutoFarmState) {
        SetTimer, SpamF_Timer, Off
        AutoFarmState := 0
    }
    if (!EnableAutoSpace && AutoSpaceState) {
        SetTimer, SpamSpace_Timer, Off
        AutoSpaceState := 0
    }
    if (!EnableAutoClick && GetKeyState("LButton")) {
        Click, Up
    }
return

ToggleAutoWalk:
    if (AutoWalkState) {
        Send, {w up}
        AutoWalkState := 0
    } else {
        Send, {w down}
        AutoWalkState := 1
    }
return

ToggleAutoFarm:
    if (AutoFarmState) {
        SetTimer, SpamF_Timer, Off
        AutoFarmState := 0
    } else {
        SetTimer, SpamF_Timer, 500
        AutoFarmState := 1
    }
return

ToggleAutoSpace:
    if (AutoSpaceState) {
        SetTimer, SpamSpace_Timer, Off
        AutoSpaceState := 0
    } else {
        SetTimer, SpamSpace_Timer, 500
        AutoSpaceState := 1
    }
return

SpamF_Timer:
    ; Sử dụng ControlSend để gửi phím vào cửa sổ game ngay cả khi không active
    ControlSend, , f, ahk_exe ONCE_HUMAN.exe
return

SpamSpace_Timer:
    ; Sử dụng ControlSend để gửi phím vào cửa sổ game ngay cả khi không active
    ControlSend, , {Space}, ahk_exe ONCE_HUMAN.exe
return