#SingleInstance Force
#Persistent
; =====================================================================
; Auto-generated by AHK Manager - 2025-11-12 20:25:49
; =====================================================================

if not A_IsAdmin
{
   Run *RunAs "%A_ScriptFullPath%"  ; Bắt buộc chạy lại bằng quyền Admin
   ExitApp
}

; Khai báo biến global cho Once Human features
global EnableAutoWalk := 1
global EnableAutoFarm := 1
global EnableAutoShoot := 1
global AutoWalkState := 0
global AutoFarmState := 0
global AutoShootState := 0

; Tạo nhóm các game cần loại trừ
GroupAdd, ExcludedGames, ahk_exe ONCE_HUMAN.exe
GroupAdd, ExcludedGames, ahk_exe DeltaForceClient-Win64-Shipping.exe
GroupAdd, ExcludedGames, ahk_exe df_garena_launcher.exe
GroupAdd, ExcludedGames, ahk_exe DeltaForce.exe
GroupAdd, ExcludedGames, ahk_exe ONCE_HUMAN
GroupAdd, ExcludedGames, ahk_exe DeltaForceClient-Win64-Shipping
GroupAdd, ExcludedGames, ahk_exe df_garena_launcher
GroupAdd, ExcludedGames, Delta Force
GroupAdd, ExcludedGames, Garena Delta Force
GroupAdd, ExcludedGames, ahk_exe dnplayer.exe
GroupAdd, ExcludedGames, ahk_exe HD-Player.exe
GroupAdd, ExcludedGames, ahk_exe BlueStacks.exe
GroupAdd, ExcludedGames, ahk_exe BlueStacksX.exe

; Chỉ kích hoạt các hotkey/hotstring bên dưới nếu KHÔNG phải là các game trong nhóm ExcludedGames
#IfWinNotActive, ahk_group ExcludedGames

SendQuickText(text) {
    DebugLog("SendQuickText triggered -> " . text)
    ClipSaved := ClipboardAll
    Clipboard := text
    ClipWait, 0.5, 1
    if (ErrorLevel) {
        DebugLog("Clipboard not ready, fallback to SendRaw")
        SendRaw, %text%
    } else {
        SendInput, ^v
    }
    Sleep, 100
    Clipboard := ClipSaved
    VarSetCapacity(ClipSaved, 0)
}

DebugLog(message) {
    OutputDebug, 🔍 %message%
}

ChooseSeedPart(options) {
    StringSplit, itemArray, options, |
    itemCount := itemArray0
    if (itemCount < 1) {
        return ""
    }

    Random, itemIndex, 1, %itemCount%
    return itemArray%itemIndex%
}

; =====================================================================
; LAUNCHER HOTKEYS
; =====================================================================

PgUp::
    RunAsUser("C:\Users\Mon\AppData\Local\Programs\Python\Python311\pythonw.exe", """c:\Users\Mon\Desktop\Protect\Mon Apps\Main\Main.pyw""", "c:\Users\Mon\Desktop\Protect\Mon Apps\Main")
return

PgDn::
    ; Kill only Main.pyw process (not all Python processes)
    KillMainPyw()
    ; Wait a bit for process to terminate
    Sleep, 500
    ; Restart Main.pyw
    RunAsUser("C:\Users\Mon\AppData\Local\Programs\Python\Python311\pythonw.exe", """c:\Users\Mon\Desktop\Protect\Mon Apps\Main\Main.pyw""", "c:\Users\Mon\Desktop\Protect\Mon Apps\Main")
return

!Space::
    OpenHermesCLI()
return

OpenHermesCLI() {
    hermesDir := "C:\Users\Mon\Desktop\Protect\Mon AI"
    hermesExe := "C:\Users\Mon\AppData\Local\Programs\Python\Python311\Scripts\hermes.exe"
    psArgs := "-NoLogo -NoExit -ExecutionPolicy Bypass -Command ""Set-Location -LiteralPath '" . hermesDir . "'; & '" . hermesExe . "' chat"""
    RunAsUser("powershell.exe", psArgs, hermesDir)
}

KillMainPyw() {
    ; Use WMI to find and kill only processes running Main.pyw
    try {
        wmi := ComObjGet("winmgmts:")
        query := "SELECT ProcessId, CommandLine FROM Win32_Process WHERE (Name = 'pythonw.exe' OR Name = 'python.exe') AND CommandLine LIKE '%Main.pyw%'"
        processes := wmi.ExecQuery(query)
        
        for process in processes {
            pid := process.ProcessId
            Process, Close, %pid%
            DebugLog("Killed Main.pyw process with PID: " . pid)
        }
    } catch e {
        ; Fallback: Try to close window by title if WMI fails
        WinClose, ahk_exe pythonw.exe
        WinClose, ahk_exe python.exe
        DebugLog("WMI failed, used WinClose fallback")
    }
}

RunAsUser(Target, Args := "", WorkingDir := "") {
    ; Get the ShellWindows collection
    shellWindows := ComObjCreate("Shell.Application").Windows
    
    ; Find the desktop window (SWC_DESKTOP = 8, SWFO_NEEDDISPATCH = 1)
    desktop := shellWindows.FindWindowSW(0, 0, 8, 0, 1)
    
    ; Check if we successfully got the desktop object
    if (desktop) {
        ; Use the desktop's application object to execute the command
        ; This inherits the user's privileges (Medium Integrity)
        desktop.Document.Application.ShellExecute(Target, Args, WorkingDir, "open", 1)
    } else {
        ; Fallback: If desktop not found, run normally (might be elevated)
        Run, %Target% %Args%, %WorkingDir%
    }
}

; CÁC PHÍM TẮT & HOTSTRING SẼ BỊ VÔ HIỆU HÓA KHI DÙNG LDPLAYER

::ff::
    SendQuickText("Hi a, A ở đâu vậy a?")
return

::xx::
    SendQuickText("Pé đến gặp a trực tiếp ok hết rồi a thanh toán cho pé tại phòng phục vụ a nha")
return

::ww::
    SendInput Hi, where are you from?
return

::www::
    SendInput 你好，你来自哪里？
return

::dd::
    SendInput Do you want massage?
return

::ddd::
    SendInput 你需要按摩吗？
return

::ss::
    SendInput Meet not same or don't like you can cancel and don't need to pay anything
return

::sss::
    SendInput 如果见面发现不一样或者不喜欢，你可以取消，不需要支付任何费用
return

::qq::
    SendInput We can meet first for you see me direct before deal, if meet and don't like you can reject and don't need to pay anything
return

::qqq::
    SendInput 可以先见面，不喜欢也没关系。如果见面后不喜欢，你可以拒绝，不需要支付任何费用
return

::nn::
    SendInput VietNam, Nice to meet you
return

::nnn::
    SendInput 越南人，很高兴认识你
return

::ii::
    SendInput Send me address if you need, I can come to you
return

::iii::
    SendInput 需要的话发地址给我，我可以过去找你
return

::,,::
    SendInput Please choose a girl and she can come to your hotel or apartment
return

::,c::
    SendInput 请选择一个女孩，她可以去你的酒店或公寓
return

::yy::
    SendInput Hello, already arrived at the lobby. Please come down.
return

::yyy::
    SendInput 你好，已经到了，现在在大堂，请下来吧。
return

::mm::
    SendInput My photos
return

::mmm::
    SendInput 我的照片
return

::cc::
    SendInput Can you take shot a photo of your key room and send it to me?
return

::ccc::
    SendInput 麻烦拍一下房卡照片发我
return

::ll::
    SendInput Text me know when you need
return

::lll::
    SendInput 好的，您需要的时候请告诉我，谢谢
return

::bb::
    SendQuickText("Dịch vụ bao gồm mát xa body nude thư giãn, tắm chung và làm tình với pé ạ")
return

::vv::
    SendQuickText("Nào a cần a nói em nha, E đến tận nơi qua a")
return

::ee::
    SendQuickText("Hi a, a ở đâu vậy?")
return

::oo::
    SendInput 1,5 milion for hour, 3,5 milion for overnight, massage and make love
return

::ooo::
    SendInput 一小时150万，包夜350万，包含按摩和做爱
return

::tt::
    SendQuickText("E có dịch vụ mát xa làm tình giá 1tr5 1 giờ, qua đêm là 3tr5")
return

::t1::
    SendQuickText("A cần thì chọn 1 pé, pé đến tận nơi qua nha")
return

::o3::
    SendInput 1.3 milions vnd for hour and 3 milions for overnight. Massage and Make love
return

::o33::
    SendInput 一小时130万，包夜300万，包含按摩和做爱
return

::o4::
    SendInput 2 milions vnd for hour and 4 milions for overnight. Massage and Make love
return

::o44::
    SendInput 一小时200万，包夜400万，包含按摩和做爱
return

::rr::
    SendQuickText("Em nhận đi khách giá 1tr5 1 giờ, qua đêm là 3tr5, A cần nói em nha")
return

::hh::
    SendQuickText("Ảnh của em a xem nhé")
return

::kk::
    SendQuickText("Dạ a cần thì lấy phòng ks nào cũng đc rồi pé đến nha")
return

::gg::
    SendQuickText("Gặp không giống hay a ko thích a có quyền từ chối và ko cần trả tiền pé gì hết. A yên tâm nhé")
return

::pp::
    SendQuickText("A cần thì chọn một pé, pé sẽ đến tận nơi a nha")
return

::jj::
    SendQuickText("Phiền a chụp giúp thẻ phòng gửi qua em để pé xác nhận qua a nha")
return

^2::
Sendinput https://github.com/Sxcution/MonViewPhone
sleep 100
return

^3::
Sendinput https://github.com/Sxcution/MonDashboard
sleep 100
return

!2::
    rulesFile := A_ScriptDir . "\MonAHK_rules.txt"
    if (FileExist(rulesFile)) {
        FileRead, rulesText, *P65001 %rulesFile%
        SendQuickText(rulesText)
    } else {
        MsgBox, 16, Error, Rules file not found: %rulesFile%
    }
return


; English chat seed generator: Ctrl+4 sends one complete, natural message.
^4::
    if (SeedChatTurn = "") {
        SeedChatTurn := 0
    }
    SeedChatTurn++
    phase := Mod(SeedChatTurn, 6)

    Loop, 20 {
        if (phase = 1) {
            opener := ChooseSeedPart("Hey|Hi|Hello|Good morning|Good afternoon|Good evening|Hey there|Hi there|Hello there|Hope you are well")
            line := ChooseSeedPart("how is your day going so far?|are you busy right now?|what are you up to right now?|did you sleep well last night?|did your day start smoothly?|are things okay on your side?|do you have a minute to chat?|are you free for a short message?|did you already eat today?|is your schedule busy today?|are you at home right now?|are you outside today?|are you working today?|is everything going fine today?|did anything interesting happen today?|are you still online?|do you usually check messages around this time?|are you having a calm day?|are you feeling okay today?|do you want to talk for a little while?")
            message := opener . ", " . line
        } else if (phase = 2) {
            activity := ChooseSeedPart("finished some work|got back home|made a cup of coffee|made some tea|had lunch|had dinner|took a short break|answered a few messages|checked my schedule|cleaned my desk|went for a short walk|finished a small task|opened WeChat|sat down for a moment|got off a call|came back from outside|charged my phone|checked the weather|read a few updates|washed my face|changed clothes|made a quick snack|checked my calendar|closed my laptop|finished a short errand|looked through my messages|put my phone on charge|came back to my room|turned on some music|finished replying to someone")
            mood := ChooseSeedPart("feeling relaxed now|not too busy right now|taking it slow today|in a pretty calm mood|trying to rest a bit|free for a short chat|just catching my breath|keeping things simple today|doing fine so far|a little tired but okay|still in a good mood|not rushing anything today|ready to chat for a bit|enjoying a quiet moment|waiting for the next thing to do|feeling better now|trying to stay focused|just relaxing for a while|not doing much at the moment|glad to have a small break")
            message := "I just " . activity . ", so I am " . mood . "."
        } else if (phase = 3) {
            reaction := ChooseSeedPart("That sounds good.|That makes sense.|I understand what you mean.|No problem at all.|Take your time with it.|That is totally fine.|I am glad to hear that.|I hope it gets easier soon.|You handled that well.|That sounds a little tiring.|That sounds comfortable.|I would probably do the same.|Thanks for telling me.|I see what you mean.|That is interesting.|That sounds like a normal day.|I hope your evening feels lighter.|That is nice to know.|I am happy you said that.|That sounds better than expected.|I know that feeling.|That is fair.|I get it now.|That sounds pretty calm.|That must have taken some energy.")
            followup := ChooseSeedPart("I can wait.|I am not in a rush.|Just reply whenever you are free.|We can talk slowly.|No need to hurry.|I like calm conversations.|I am still here.|I will check again later.|That works for me.|I do not mind at all.|We can keep it simple.|I just wanted to ask.|I only wanted to say hello.|I can reply later too.|It is okay if you are busy.|We can continue when you have time.|I like talking this way.|A slow chat is fine with me.|You can answer when it is convenient.|I am just relaxing anyway.")
            message := reaction . " " . followup
        } else if (phase = 4) {
            topicQuestion := ChooseSeedPart("Do you usually listen to music while you work?|What kind of music do you like these days?|Do you prefer coffee or tea?|What food do you usually like for dinner?|Do you like quiet places or busy places?|Do you usually go out on weekends?|Do you prefer texting or voice messages?|Do you watch movies often?|What kind of movies do you enjoy?|Do you usually sleep late?|Do you wake up early most days?|Do you like taking photos when you go out?|Do you check WeChat often during the day?|Do you usually reply fast or slow?|Do you like simple conversations?|Do you prefer staying home or going outside?|Do you have any plans for later today?|Do you like rainy weather?|Do you like sunny days more?|Do you usually drink coffee in the afternoon?|Do you enjoy walking around at night?|Do you like trying new food?|Do you often talk with friends online?|Do you prefer a busy day or a quiet day?|Do you like making plans or deciding later?")
            message := topicQuestion
        } else if (phase = 5) {
            task := ChooseSeedPart("finish something|step away for a minute|make a quick call|reply to another message|get some water|charge my phone|check something nearby|take a short break|get back to work|prepare something|look at my schedule|handle a small task|make a quick note|answer a call|clean up a little|check one more thing|send a message to someone|rest my eyes for a moment|walk around for a minute|take care of something")
            returnLine := ChooseSeedPart("I will message you again later.|I will come back after that.|I will check your reply when I return.|we can continue after that.|I will not be away for too long.|I will reply when I am back.|I will open the chat again later.|we can talk more when I am done.|I will be back soon.|I will read your message later.")
            message := "I need to " . task . ", but " . returnLine
        } else {
            starter := ChooseSeedPart("By the way|Also|One more thing|Just asking|Small question|I was wondering|Before I forget|Another random thought|Something simple|Quick question")
            thought := ChooseSeedPart("what time do you usually sleep?|what are you doing after work?|do you have a favorite drink?|do you like quiet evenings?|do you usually plan your day?|do you prefer short messages?|do you like chatting at night?|do you usually eat at home?|do you like morning or evening better?|do you often use your phone before sleeping?|do you like simple food?|do you usually take breaks during work?|do you prefer warm weather?|do you like walking outside?|do you check messages before bed?|do you like talking about daily life?|do you enjoy slow conversations?|do you usually keep your phone nearby?|do you like staying busy?|do you like a calm routine?")
            message := starter . ", " . thought
        }

        if (message != LastSeedMessage) {
            Break
        }
    }

    LastSeedMessage := message
    SendInput, %message%
return

#IfWinActive

; =====================================================================
; ONCE HUMAN SPECIFIC HOTKEYS
; =====================================================================
; Load Settings from INI file (Default to 1 if not found)
IniRead, EnableAutoWalk, MonAHK_Settings.ini, OnceHuman, EnableAutoWalk, 1
IniRead, EnableAutoFarm, MonAHK_Settings.ini, OnceHuman, EnableAutoFarm, 1
IniRead, EnableAutoShoot, MonAHK_Settings.ini, OnceHuman, EnableAutoShoot, 1

; Debug: Kiểm tra giá trị đã load
OutputDebug, 🔍 EnableAutoWalk = %EnableAutoWalk%
OutputDebug, 🔍 EnableAutoFarm = %EnableAutoFarm%
OutputDebug, 🔍 EnableAutoShoot = %EnableAutoShoot%

; --- Hotkeys with Conditional Logic ---

; Only activate hotkeys when game is active
#If WinActive("ahk_exe ONCE_HUMAN.exe")
NumpadAdd::
    ; Check if feature is enabled before toggling
    if (EnableAutoWalk) {
        GoSub, ToggleAutoWalk
    }
return

!f::
    ; Check if feature is enabled before toggling
    if (EnableAutoFarm) {
        GoSub, ToggleAutoFarm
    }
return

F4::
    ; Check if feature is enabled before toggling
    if (EnableAutoShoot) {
        GoSub, ToggleAutoShoot
    }
return
#If

; Menu Hotkey (Always Active in Game)
#If WinActive("ahk_exe ONCE_HUMAN.exe")
F5::
    ; Destroy previous GUI to ensure fresh state
    Gui, OnceHuman:Destroy
    Gui, OnceHuman:New, +AlwaysOnTop +ToolWindow, Once Human Menu
    Gui, OnceHuman:Font, s10, Segoe UI
    
    Gui, OnceHuman:Add, Text, x10 y10, Master Switches (Enable/Disable Hotkeys):
    
    ; Checkbox Auto Walk
    Gui, OnceHuman:Add, Checkbox, x20 y+10 vCbEnableAutoWalk gGuiUpdateSwitches Checked%EnableAutoWalk%, Enable Auto Walk (Numpad +)
    
    ; Checkbox Auto Farm
    Gui, OnceHuman:Add, Checkbox, x20 y+10 vCbEnableAutoFarm gGuiUpdateSwitches Checked%EnableAutoFarm%, Enable Auto Farm (Alt + F)
    
    ; Checkbox Auto Shoot
    Gui, OnceHuman:Add, Checkbox, x20 y+10 vCbEnableAutoShoot gGuiUpdateSwitches Checked%EnableAutoShoot%, Enable Auto Shoot (F4)
    
    Gui, OnceHuman:Show, Center NoActivate, Once Human Controls
return
#If

; --- Subroutines ---

GuiUpdateSwitches:
    Gui, OnceHuman:Submit, NoHide
    EnableAutoWalk := CbEnableAutoWalk
    EnableAutoFarm := CbEnableAutoFarm
    EnableAutoShoot := CbEnableAutoShoot
    
    ; Save Settings to INI
    IniWrite, %EnableAutoWalk%, MonAHK_Settings.ini, OnceHuman, EnableAutoWalk
    IniWrite, %EnableAutoFarm%, MonAHK_Settings.ini, OnceHuman, EnableAutoFarm
    IniWrite, %EnableAutoShoot%, MonAHK_Settings.ini, OnceHuman, EnableAutoShoot
    
    ; Stop any running actions if features are disabled
    if (!EnableAutoWalk && AutoWalkState) {
        Send, {w up}
        AutoWalkState := 0
    }
    if (!EnableAutoFarm && AutoFarmState) {
        SetTimer, SpamF_Timer, Off
        AutoFarmState := 0
    }
    if (!EnableAutoShoot && AutoShootState) {
        Send, {LButton up}
        AutoShootState := 0
    }
return

ToggleAutoWalk:
    if (AutoWalkState) {
        Send, {w up}
        AutoWalkState := 0
    } else {
        Send, {w down}
        AutoWalkState := 1
    }
return

ToggleAutoFarm:
    if (AutoFarmState) {
        SetTimer, SpamF_Timer, Off
        AutoFarmState := 0
    } else {
        SetTimer, SpamF_Timer, 500
        AutoFarmState := 1
    }
return

ToggleAutoShoot:
    if (AutoShootState) {
        Send, {LButton up}
        AutoShootState := 0
    } else {
        Send, {LButton down}
        AutoShootState := 1
    }
return

SpamF_Timer:
    ; Sử dụng ControlSend để gửi phím vào cửa sổ game ngay cả khi không active
    ControlSend, , f, ahk_exe ONCE_HUMAN.exe
return
